# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ROM/ROM.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM}]

# IP: bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_blk_mem_gen_0_0 || ORIG_REF_NAME==ROM_blk_mem_gen_0_0}]

# IP: bd/ROM/ip/ROM_xlconstant_0_0/ROM_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_xlconstant_0_0 || ORIG_REF_NAME==ROM_xlconstant_0_0}]

# XDC: bd/ROM/ROM_ooc.xdc
