# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/VivadoProjects/Ex1/ROM/ROM.cache/wt [current_project]
set_property parent.project_path E:/VivadoProjects/Ex1/ROM/ROM.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/VivadoProjects/Ex1/ROM/ROM.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/VivadoProjects/Ex1/ROM/ROM.srcs/sources_1/bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM.coe
read_verilog -library xil_defaultlib E:/VivadoProjects/Ex1/ROM/ROM.srcs/sources_1/imports/hdl/ROM_wrapper.v
add_files E:/VivadoProjects/Ex1/ROM/ROM.srcs/sources_1/bd/ROM/ROM.bd
set_property used_in_implementation false [get_files -all e:/VivadoProjects/Ex1/ROM/ROM.srcs/sources_1/bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/VivadoProjects/Ex1/ROM/ROM.srcs/sources_1/bd/ROM/ROM_ooc.xdc]
set_property is_locked true [get_files E:/VivadoProjects/Ex1/ROM/ROM.srcs/sources_1/bd/ROM/ROM.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top ROM_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef ROM_wrapper.dcp

catch { report_utilization -file ROM_wrapper_utilization_synth.rpt -pb ROM_wrapper_utilization_synth.pb }
