# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.cache/wt [current_project]
set_property parent.project_path E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/VivadoProjects/Ex1/CPU_BB/CPU_BB.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/ALU/ALU.srcs/sources_1/new/ALU.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/new/Binary2BCD.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/FLAG/FLAG.srcs/sources_1/new/FLAG.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/new/IO_2.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/PC/PC.srcs/sources_1/new/PC.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/Ex1_Register/Ex1_Register.srcs/sources_1/new/Register.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/CtrlUnit/CtrlUnit.srcs/sources_1/new/OP_define.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/CtrlUnit/CtrlUnit.srcs/sources_1/new/ctrlunit.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/new/divider.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/imports/Ex1/myROM_2.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/new/result_process.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/new/seg.v
  E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/sources_1/imports/sources_1/new/CPU_A_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/constrs_1/imports/new/Keyboard_pin.xdc
set_property used_in_implementation false [get_files E:/VivadoProjects/Ex1/CPU_BB/CPU_BB.srcs/constrs_1/imports/new/Keyboard_pin.xdc]


synth_design -top CPU_A_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef CPU_A_top.dcp

catch { report_utilization -file CPU_A_top_utilization_synth.rpt -pb CPU_A_top_utilization_synth.pb }
